### PR TITLE
Add a `memberTo` field

### LINKED ISSUE #12: Add a "member to" field
Add a field on each user that says to when they are members in the chapter. It will not be retrieved by KTHs ldap api

### PR DESCRIPTION
**Pull request by foodelevator**
Closes #12

### CODE REVIEW

**Review by Herkarl — COMMENTED** [review]
I think it is reasonable to have an expire date rather than just a bool.
Will we be able to get the data for when a membership expires?
I suppose that we know that all THS memberships expires at the same time, currently at least.

The advantage with having a bool I suppose is that we get a complete membership list from THS anyway, so we would be able to just set everyone not in that list as not a member anyway.

The advantage with having an expire-date would be that it would prevent anyone from having access for too long.

**Comment by foodelevator** [comment]
The membership list we get from THS reportedly has an expiry date for each user. I guess everyone most of the time should have the same though as you pointed out.
But if we would set everyone not on the list membership to false we it would be harder to manage people we think are members but perhaps THS doesn't. I guess e.g. those in Ordförandeordern would be affected here

**Review by Herkarl — APPROVED** [review]
Very true! Would include Hedersmedlemmar as well

Perhaps it would be an idea to give a warning in the frontend when updating the date of someone with a date far into the future (which I suppose would be the most reasonable way to implement someone with a permanent membership without adding another field to the table).

This situation could happen if an Ordf. emeritus decides to be a support member to THS (e.g. Plutten), or takes a break from their studies and then resumes them.

But perhaps it is too much of an edge-case to be something to worry about :p

**Review by Herkarl — COMMENTED** [review]
After thinking a bit more about it, I would argue for having a separate field for "permanent member". I'm not particularly fond of magic values, and the cost is not really a problem. 
The risk of accidently overwriting the date would not exist, and the API would be clearer (or simpler to write in a clear way). 

But otherwise lgtm

**Comment by foodelevator** [comment]
I think I agree. My thought was that it would be easier to check if someone is a chapter member if permanent members get an and date far into the future, but it still pretty easy:tm: to check a bool and a date ^^

**Pull request merged**
